[package]
name = "projeto"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
ctrlc = "3.4.4"
global_counter = "0.2.2"
rppal = "0.17.1"
rust_socketio = { version = "0.6.0", features = ["async"] }
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
