[package]
name = "fse_trab_1_second_floor"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
ctrlc = "3.4.4"
openssl = { version = "0.10.64", features = ["vendored"] }
rppal = "0.17.1"
rust_socketio = "0.6.0"
serde = "1.0.201"
serde_json = "1.0.117"
